### ISSUE TITLE
Student Life section slider not responsive.

### ISSUE THREAD

**Issue by vibhanshujainiiitr** [iamaniiitian/home#13]
The slider is not responsive in mobile view. Also, try it is not changing on its own as of now. Try to the auto slider on this. 
Thanks to Ankit IIIT Guwahati.
If you can come up with some better slider then it will be really appreciable.
You can take help from this site: http://cssslider.com/

**Comment by iamankitkumar08062001** [comment]
Assign this to me as I already have the replacement ready and I can make this responsive
